### PR TITLE
Extract permission request code into separate API.

### PR DESCRIPTION
**Pull request by freezy**
This moves the Android code which requests the Bluetooth/location permission into a separate method so it can be uses in a separate API.

Not sure if the same thing needs to be done for iOS, @jaumard?

### CODE REVIEW

**Comment by freezy** [comment]
Tested successfully in app, good to merge now.

**Review by jaumard — APPROVED** [review]
LGTM, I've published this non null safe to 1.2.1

**Comment by jaumard** [comment]
Changelog must be merged, but pub spec of master should be taken here

**Comment by freezy** [comment]
Conflicts resolved, version is at 2.0.0 now. That's correct?

**Comment by jaumard** [comment]
Yes I will need to bump to 2.1.0 to push that feature also in null safe but all good for now

**Comment by freezy** [comment]
Gotcha, merging.

**Pull request merged**
